# Generated by Django 5.1.3 on 2024-11-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollarRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_rub_rate', models.FloatField()),
                ('date_time_request', models.DateTimeField()),
            ],
        ),
    ]
