# Generated by Django 5.1.3 on 2024-11-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dollar_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dollarratehistory',
            options={'verbose_name': 'Dollar Rate'},
        ),
    ]
